galaxy_info:
  role_name: caddy
  author: Sam Doran
  description: Install and manage Caddy
  company: ~
  license: Apache 2.0
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8

    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal

    - name: Debian
      versions:
        - stretch
        - jessie
        - buster

  galaxy_tags:
    - system
    - caddy
    - web
    - http

dependencies: []
