- name: Download and install custom Caddy build
  hosts: all
  become: yes
  vars:
    caddy_download_custom_build: yes

  tasks:
    - debug:
        msg: >-
          Testing with Ansible {{ ansible_version.full }} using Python {{ ansible_facts.python_version }}
          on {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}

    - import_role:
        name: caddy

- name: Verify
  hosts: all
  become: yes

  tasks:
    - name: Test that Caddy is running
      uri:
        url: http://127.0.0.1
        status_code: 200
        return_content: yes
      register: result
      until:
        - result.status == 200
        - "'Caddy web server' in result.content"
      retries: 10
      delay: 5
