- name: Stop Caddy
  service:
    name: stopped
  tags:
    - caddy

- name: Remove Caddy v1 files
  file:
    state: absent
    path: "{{ item }}"
  tags:
    - caddy
  loop:
    - /etc/caddy/caddy.conf
    - /usr/local/bin/caddy
    - /var/tmp/caddy

- name: Remove Caddy user
  user:
    name: "{{ caddy_user }}"
    state: absent
  tags:
    - caddy

- name: Remove Caddy group
  group:
    name: "{{ caddy_group }}"
    state: absent
  tags:
    - caddy

- name: Remove SSL Caddy directory
  file:
    path: "{{ _caddy_ssl_path[ansible_facts['os_family']] | default('/etc/pki/tls/caddy') }}"
    state: absent
  tags:
    - caddy

- name: Remove service files
  file:
    path: "{{ _caddy_service_files[ansible_facts.service_mgr] }}"
    state: absent
  tags:
    - caddy
