- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - default.yml
      paths:
        - vars
  tags:
    - always
    - caddy

- import_tasks: install.yml
