---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install ufw
  apt: 
    name: ufw
    state: present

- name: Allow ssh in UFW
  ufw: 
    rule: allow
    port: '22' 
    proto: tcp

- name: Allow http in UFW
  ufw: 
    rule: allow
    port: '80'
    proto: tcp

- name: Allow https in UFW
  ufw: 
    rule: allow 
    port: '443'
    proto: tcp

- name: sshd configuration file update
  template:
    src: templates/sshd_config.j2 
    dest: /etc/ssh/sshd_config
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
  - restart sshd

- name: Set firewall default policy
  ufw: 
    state: enabled 
    policy: reject

- name: Install logrotate config
  template: 
    src: templates/logrotate.j2 
    dest: /etc/logrotate.d/rsyslog

- name: Install htop
  apt: 
    name: htop
    state: present

- name: Install ncdu
  apt: 
    name: ncdu
    state: present

- name: Install apt-transport-https
  apt: 
    name: apt-transport-https
    state: present

- name: Ensure group "bitraft" exists
  group:
    name: bitraft
    state: present

- name: Creates directory
  file:
    path: /etc/bitraft
    state: directory
    owner: root
    group: bitraft
    mode: 0750

- name: Install Config
  template: 
    src: templates/config.json.j2 
    dest: /etc/bitraft/config.json