---
  - name: Create speaker user
    user:
      name: speaker
      shell: /bin/bash
      groups: 
        - spamchamp
      append: yes

  - name: Install Service
    template: 
      src: templates/service.j2 
      dest: /etc/systemd/system/speaker.service