_caddy_url_values:
  platform:
    linux: linux
    macosx: darwin
  architecture:
    x86_64: 'amd64'
    i386: '386'
    armv7l: arm7

_caddy_service_files:
  systemd: /lib/systemd/system/caddy.service
  upstart: /etc/init/caddy.conf
  init: /etc/init.d/caddy

_platform: "{{ ansible_facts['system'] | lower }}"
_architecture: "{{ _caddy_url_values['architecture'][ansible_facts['architecture']] }}"
_plugins: "{% for option in caddy_plugins %}&p={{ option | replace('/', '%2F') }}{% endfor %}"

_caddy_ssl_path:
  Debian: /etc/ssl/caddy
