---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure Netdata
  license: MIT

  min_ansible_version: 2.0

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Debian
      versions:
        - buster
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - bionic
        - dingo
        - focal
        - precise
        - trusty
        - xenial

  galaxy_tags:
    - system
    - performance
    - monitoring

dependencies: []
