dist: focal
language: python
services: docker

env:
  global:
    - ROLE_NAME: caddy
  matrix:
    - MOLECULE_DISTRIBUTION: centos7
    - MOLECULE_DISTRIBUTION: centos8
    - MOLECULE_DISTRIBUTION: ubuntu18
    - MOLECULE_DISTRIBUTION: ubuntu20
    - MOLECULE_DISTRIBUTION: debian8
      ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python
    - MOLECULE_DISTRIBUTION: debian9
    - MOLECULE_DISTRIBUTION: debian10
    - MOLECULE_DISTRIBUTION: fedora31
    - MOLECULE_DISTRIBUTION: fedora32

install:
  - pip install molecule[lint]==3.0.6 docker

before_script:
  # Remove "ansible-role-" prefix from role name
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - ansible-galaxy install -n -r molecule/default/requirements.yml
  # Run tests
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
