---
- name: Provision hosts for bitraft
  hosts: all
  remote_user: root
  
  roles:
    - {role: 'common', tags: ['common']}
    - {role: 'geerlingguy.redis', tags: ['redis']}
    - {role: 'speaker', tags: ['speaker']}
    - {role: 'caddy-ansible', tags: ['caddy']}
    - {role: 'api', tags: ['api']}
