- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Test that Caddy is running
      uri:
        url: http://127.0.0.1
        status_code: 200
        return_content: yes
      register: result
      until:
        - result.status == 200
        - result.content is regex('Caddy (works!|web server)')
      retries: 10
      delay: 5
