---
  - name: Create api user
    user:
      name: api
      shell: /bin/bash
      groups: 
        - bitraft
      append: yes

  - name: Creates directory
    file:
      path: /var/bitraft
      state: directory
      owner: bitraft
      group: bitraft
      mode: 0750

  - name: Install Api Service
    template: 
      src: templates/service.j2 
      dest: /etc/systemd/system/api.service

  - name: Install Api proxy config
    template: 
      src: templates/Caddyfile.j2
      dest: /etc/caddy/Caddyfile
    notify: Restart caddy