---
galaxy_info:
  author: caddy_ansible
  role_name: caddy_ansible
  description: Installs and configures a Caddy webserver
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - stretch
        - buster
    - name: Fedora
      versions:
        - 29
  galaxy_tags:
    - system
    - web
dependencies: []
