dependency:
  name: galaxy
  enabled: no
driver:
  name: docker
lint: |
  ansible-lint -x 204,208,403,502
  yamllint -c molecule/yamllint.yml .
platforms:
  - name: caddy-test-cleanup_v1-${MOLECULE_DISTRIBUTION:-centos8}
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos8}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
scenario:
  name: cleanup_v1
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - destroy
verifier:
  name: ansible
