name: Bot

on:
    workflow_dispatch:
    push:
        branches:
            - "master"
        paths:
            - services/bot/**
            - pkg/**
            - go.mod
            - go.sum

jobs:
    Bot:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Setup SSH
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
                  SSH_KEY: ${{ secrets.KEY }}
              run: |
                  mkdir ~/.ssh
                  echo "$SSH_KEY" > ~/.ssh/id_rsa
                  touch ~/.ssh/known_hosts
                  chmod 600 ~/.ssh/id_rsa
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                  ssh-add ~/.ssh/id_rsa
                  ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

            - name: Build
              working-directory: ./web
              run: |
                  yarn install
                  yarn build

            - name: Build
              working-directory: ./services/bot
              run: |
                  go build

            - name: Deploy
              working-directory: ./services/bot
              run: |
                  scp bot ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/spamchampbot

            - name: Restart
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: systemctl restart spamchampbot

            - name: Deploy Frontend
              uses: peaceiris/actions-gh-pages@v2.3.1
              env:
                  ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./web/public
