name: ingester

on:
    workflow_dispatch:
    push:
        branches:
            - "master"
        paths:
            - services/ingester/**
            - pkg/**

jobs:
    ingester:
        runs-on: ubuntu-latest
        steps:
            - name: Setup SSH
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
                  SSH_KEY: ${{ secrets.KEY }}
              run: |
                  mkdir ~/.ssh
                  echo "$SSH_KEY" > ~/.ssh/id_rsa
                  touch ~/.ssh/known_hosts
                  chmod 600 ~/.ssh/id_rsa
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                  ssh-add ~/.ssh/id_rsa
                  ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

            - name: Build
              run: |
                  ls -lsa 
                  go build

            - name: Stop
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: systemctl stop ingester

            - name: Deploy
              working-directory: ./services/ingester
              run: |
                  scp ingester ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ingester

            - name: Start
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: systemctl start ingester