name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build relaybroker
      with:
        repository: gempir/relaybroker
      run: |
        go get
        go build

    - name: Stop Relaybroker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: systemctl stop relaybroker

    - name: Deploy Relaybroker
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        rm: true
        source: "relaybroker"
        target: "/home/spamchampbot/relaybroker"

    - name: Start Relaybroker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: systemctl start relaybroker

    # spamchamp

    - uses: actions/checkout@v1
    - name: Build web
      working-directory: ./web
      run: |
        yarn install
        yarn build
      
    - name: Build Bot
      working-directory: ./bot
      run: |
        go get
        go build

    - name: Stop Backend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: systemctl stop spamchampbot

    - name: Deploy Backend
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        rm: true
        source: "bot/bot"
        target: "/home/spamchampbot"

    - name: Start Backend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: systemctl start spamchampbot

    - name: Deploy Frontend
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./web/public