name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build web
      working-directory: ./web
      run: |
        yarn install
        yarn build

    - name: Install Go
      uses: actions/setup-go@v1
      
    - name: Build Bot
      working-directory: ./bot
      run: |
        go get
        go test ./...
        go build

    - name: Deploy Backend
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "bot/bot"
        target: "/home/spamchampbot/"
        
    - name: Deploy Frontend
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./web/public

