name: Provision

on:
  issues:
    types: [opened,edited]

jobs:
  Provision:
    name: Provision
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'provision')
    steps:
      - uses: actions/checkout@v1
      
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v1
        env:
          ANSIBLE_PASS: ${{secrets.ANSIBLE_PASS}}
          middle_name: The
          Last_Name: Octocat
        with:
          playbook: playbook.yml
          directory: ./ansible
          key: ${{secrets.KEY}}
          options: |
            --verbose
            --vault-password-file vault_pass.sh