name: Provision

on:
  issues:
    types: [opened,edited]

jobs:
  Provision:
    name: Provision
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'provision')
    steps:
      - uses: actions/checkout@v1
      
      - name: Set env
      run: echo ::set-env name=ANSIBLE_PASS::${{secrets.ANSIBLE_PASS}}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v1
        with:
          playbook: playbook.yml
          directory: ./ansible
          key: ${{secrets.KEY}}
          options: |
            --inventory hosts
            --verbose
            --vault-password-file vault_pass.sh