name: Relaybroker

on:
  workflow_dispatch:

jobs:
  Relaybroker:
    name: Relaybroker
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_KEY: ${{ secrets.KEY }}
        run: |
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - uses: actions/checkout@v1
        with:
          repository: gempir/relaybroker
          ref: master
      - name: Build relaybroker
        working-directory: ./../relaybroker
        run: |
          go get
          go build

      - name: Stop Bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: systemctl stop spamchampbot

      - name: Stop Relaybroker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: systemctl stop relaybroker

      - name: Deploy Relaybroker
        working-directory: ./../relaybroker
        run: |
          scp relaybroker ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/relaybroker/

      - name: Start Relaybroker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: systemctl start relaybroker

      - name: Start Relaybroker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: systemctl start spamchampbot
