name: Relaybroker

on:
  issues:
    types: [opened, edited]

jobs:
  Relaybroker:
    name: Relaybroker
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'relaybroker')
    steps:
      - uses: actions/checkout@v1
        with:
          repository: gempir/relaybroker
          ref: master
      - name: Build relaybroker
        working-directory: ./../relaybroker
        run: |
          go get
          go build

      - name: Stop Relaybroker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: systemctl stop relaybroker

      # - name: Deploy Relaybroker
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     port: ${{ secrets.PORT }}
      #     rm: true
      #     source: "../"
      #     target: "/home/relaybroker/"

      - name: Deploy Relaybroker
        working-directory: ./../relaybroker
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_KEY: ${{ secrets.KEY }}
        run: |
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ls -lsa
          scp relaybroker ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/relaybroker/

      - name: Start Relaybroker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: systemctl start relaybroker
